class PlayerAttributeOption:
    OPT_NONE = "NONE"

    OPT_A = "A"
    OPT_B = "B"
    OPT_C = "C"
    OPT_L = "L"
    OPT_N = "N"
    OPT_O = "O"
    OPT_R = "R"
    OPT_S = "S"
    OPT_Y = "Y"

    OPT_NA = "NA"

    OPT_0 = "0"
    OPT_1 = "1"
    OPT_2 = "2"
    OPT_3 = "3"
    OPT_4 = "4"
    OPT_5 = "5"
    OPT_6 = "6"
    OPT_7 = "7"
    OPT_8 = "8"
    OPT_9 = "9"
    OPT_10 = "10"
    OPT_11 = "11"
    OPT_12 = "12"
    OPT_13 = "13"
    OPT_14 = "14"
    OPT_15 = "15"
    OPT_16 = "16"
    OPT_17 = "17"
    OPT_18 = "18"
    OPT_19 = "19"
    OPT_20 = "20"
    OPT_21 = "21"
    OPT_22 = "22"
    OPT_23 = "23"
    OPT_24 = "24"
    OPT_25 = "25"
    OPT_26 = "26"
    OPT_27 = "27"
    OPT_28 = "28"
    OPT_29 = "29"
    OPT_30 = "30"
    OPT_31 = "31"
    OPT_32 = "32"

    OPT_M1 = "-1"
    OPT_M2 = "-2"
    OPT_M3 = "-3"
    OPT_M4 = "-4"
    OPT_M5 = "-5"
    OPT_M6 = "-6"
    OPT_M7 = "-7"

    OPT_WHITE = "WHITE"
    OPT_BLACK = "BLACK"
    OPT_RED = "RED"
    OPT_BLUE = "BLUE"
    OPT_PURPLE = "PURPLE"
    OPT_CYAN = "CYAN"
    OPT_YELLOW = "YELLOW"
    OPT_GREEN = "GREEN"
    OPT_SAME = "SAME"

    OPT_SHORT = "SHORT"
    OPT_STANDARD = "STANDARD"
    OPT_LONG = "LONG"
    OPT_AUTO = "AUTO"
    OPT_UNTUCKED = "UNTUCKED"

    OPT_GK = "GK"
    OPT_SW = "SW"
    OPT_CB = "CB"
    OPT_SB = "SB"
    OPT_DM = "DM"
    OPT_WB = "WB"
    OPT_CM = "CM"
    OPT_SM = "SM"
    OPT_AM = "AM"
    OPT_WF = "WF"
    OPT_SS = "SS"
    OPT_CF = "CF"

    OPT_EARLY = "EARLY"
    OPT_EARLY_LASTING = "EARLY/LASTING"
    OPT_STANDARD = "STANDARD"
    OPT_STANDARD_LASTING = "STANDARD/LASTING"
    OPT_LATE = "LATE"
    OPT_LATE_LASTING = "LATE/LASTING"

    OPT_BUILD = "BUILD"
    OPT_SPECIAL = "SPECIAL"
    OPT_PRESET = "PRESET"

    OPT_PATTERN = "PATTERN"
    OPT_RGB = "RGB"

    OPT_BLACK_1 = "BLACK 1"
    OPT_BLACK_2 = "BLACK 2"
    OPT_DARK_GREY_1 = "DARK GREY 1"
    OPT_DARK_GREY_2 = "DARK GREY 2"
    OPT_BROWN_1 = "BROWN 1"
    OPT_BROWN_2 = "BROWN 2"
    OPT_LIGHT_BLUE_1 = "LIGHT BLUE 1"
    OPT_LIGHT_BLUE_2 = "LIGHT BLUE 2"
    OPT_BLUE_1 = "BLUE 1"
    OPT_BLUE_2 = "BLUE 2"
    OPT_GREEN_1 = "GREEN 1"
    OPT_GREEN_2 = "GREEN 2"

    OPT_BALD = "BALD"
    OPT_BUZZ_CUT = "BUZZ CUT"
    OPT_VERY_SHORT_1 = "VERY SHORT 1"
    OPT_VERY_SHORT_2 = "VERY SHORT 2"
    OPT_STRAIGHT_1 = "STRAIGHT 1"
    OPT_STRAIGHT_2 = "STRAIGHT 2"
    OPT_CURLY_1 = "CURLY 1"
    OPT_CURLY_2 = "CURLY 2"
    OPT_PONYTAIL_1 = "PONYTAIL 1"
    OPT_PONYTAIL_2 = "PONYTAIL 2"
    OPT_DREADLOCKS = "DREADLOCKS"
    OPT_PULLED_BACK = "PULLED BACK"
    OPT_SPECIAL = "SPECIAL"
