class PlayerAttributeOption:
    OPT_NONE = "NONE"

    OPT_A = "A"
    OPT_B = "B"
    OPT_C = "C"
    OPT_L = "L"
    OPT_N = "N"
    OPT_O = "O"
    OPT_R = "R"
    OPT_S = "S"
    OPT_Y = "Y"

    OPT_0 = "0"
    OPT_1 = "1"
    OPT_2 = "2"
    OPT_3 = "3"
    OPT_4 = "4"
    OPT_5 = "5"
    OPT_6 = "6"
    OPT_7 = "7"
    OPT_8 = "8"
    OPT_9 = "9"
    OPT_10 = "10"
    OPT_11 = "11"
    OPT_12 = "12"
    OPT_13 = "13"
    OPT_14 = "14"
    OPT_15 = "15"
    OPT_16 = "16"

    OPT_M1 = "-1"
    OPT_M2 = "-2"
    OPT_M3 = "-3"
    OPT_M4 = "-4"
    OPT_M5 = "-5"
    OPT_M6 = "-6"
    OPT_M7 = "-7"

    OPT_WHITE = "WHITE"
    OPT_BLACK = "BLACK"
    OPT_RED = "RED"
    OPT_BLUE = "BLUE"
    OPT_PURPLE = "PURPLE"
    OPT_CYAN = "CYAN"
    OPT_YELLOW = "YELLOW"
    OPT_GREEN = "GREEN"
    OPT_SAME = "SAME"

    OPT_SHORT = "SHORT"
    OPT_STANDARD = "STANDARD"
    OPT_LONG = "LONG"
    OPT_AUTO = "AUTO"

    OPT_GK = "GK"
    OPT_SW = "SW"
    OPT_CB = "CB"
    OPT_SB = "SB"
    OPT_DM = "DM"
    OPT_WB = "WB"
    OPT_CM = "CM"
    OPT_SM = "SM"
    OPT_AM = "AM"
    OPT_WF = "WF"
    OPT_SS = "SS"
    OPT_CF = "CF"

    OPT_EARLY = "EARLY"
    OPT_EARLY_LASTING = "EARLY/LASTING"
    OPT_STANDARD = "STANDARD"
    OPT_STANDARD_LASTING = "STANDARD/LASTING"
    OPT_LATE = "LATE"
    OPT_LATE_LASTING = "LATE/LASTING"

    OPT_BUILD = "BUILD"
    OPT_SPECIAL = "SPECIAL"
    OPT_PRESET = "PRESET"
