from bidict import bidict


class EditorConfig:
    NATIONALITIES = bidict(
        {
            0: "AUSTRIA",
            1: "BELGIUM",
            2: "BULGARIA",
            3: "CROATIA",
            4: "CZECH REPUBLIC",
            5: "DENMARK",
            6: "ENGLAND",
            7: "FINLAND",
            8: "FRANCE",
            9: "GERMANY",
            10: "GREECE",
            11: "HUNGARY",
            12: "IRELAND",
            13: "ITALY",
            14: "LATVIA",
            15: "NETHERLANDS",
            16: "NORTHERN IRELAND",
            17: "NORWAY",
            18: "POLAND",
            19: "PORTUGAL",
            20: "ROMANIA",
            21: "RUSSIA",
            22: "SCOTLAND",
            23: "SERBIA AND MONTENEGRO",
            24: "SLOVAKIA",
            25: "SLOVENIA",
            26: "SPAIN",
            27: "SWEDEN",
            28: "SWITZERLAND",
            29: "TURKEY",
            30: "UKRAINE",
            31: "WALES",
            32: "ANGOLA",
            33: "CAMEROON",
            34: "COTE D'IVOIRE",
            35: "GHANA",
            36: "NIGERIA",
            37: "SOUTH AFRICA",
            38: "TOGO",
            39: "TUNISIA",
            40: "COSTA RICA",
            41: "MEXICO",
            42: "TRINIDAD AND TOBAGO",
            43: "UNITED STATES",
            44: "ARGENTINA",
            45: "BRAZIL",
            46: "CHILE",
            47: "COLOMBIA",
            48: "ECUADOR",
            49: "PARAGUAY",
            50: "PERU",
            51: "URUGUAY",
            52: "IRAN",
            53: "JAPAN",
            54: "SAUDI ARABIA",
            55: "SOUTH KOREA",
            56: "AUSTRALIA",
            57: "BOSNIA AND HERZEGOVINA",
            58: "ESTONIA",
            59: "ISRAEL",
            60: "HONDURAS",
            61: "JAMAICA",
            62: "PANAMA",
            63: "BOLIVIA",
            64: "VENEZUELA",
            65: "CHINA",
            66: "UZBEKISTAN",
            67: "ALBANIA",
            68: "CYPRUS",
            69: "ICELAND",
            70: "MACEDONIA",
            71: "ARMENIA",
            72: "BELARUS",
            73: "GEORGIA",
            74: "LIECHTENSTEIN",
            75: "LITHUANIA",
            76: "ALGERIA",
            77: "BENIN",
            78: "BURKINA FASO",
            79: "CAPE VERDE",
            80: "CONGO",
            81: "DR CONGO",
            82: "EGYPT",
            83: "EQUATORIAL GUINEA",
            84: "GABON",
            85: "GAMBIA",
            86: "GUINEA",
            87: "GUINEA-BISSAU",
            88: "KENYA",
            89: "LIBERIA",
            90: "LIBYA",
            91: "MALI",
            92: "MOROCCO",
            93: "MOZAMBIQUE",
            94: "SENEGAL",
            95: "SIERRA LEONE",
            96: "ZAMBIA",
            97: "ZIMBABWE",
            98: "CANADA",
            99: "GRENADA",
            100: "GUADELOUPE",
            101: "MARTINIQUE",
            102: "NETHERLANDS ANTILLES",
            103: "OMAN",
            104: "NEW ZEALAND",
            105: "FREE NATIONALITY",
        }
    )
